services:
  - type: web
    name: elite8-digital
    env: node
    buildCommand: npm install && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_BASE_URL
        sync: false
    healthCheckPath: /
    autoDeploy: true
